const express = require("express");
const cors = require("cors");

const app = express();

app.use(cors({
  origin: [
    "https://dependablediamondtransportation.com",
    "https://www.dependablediamondtransportation.com"
  ],
  methods: ["GET", "POST", "OPTIONS"],
  allowedHeaders: ["Content-Type"]
}));

app.use(express.json());

const SHOP = process.env.SHOPIद्योगिक_SHOP;
const CLIENT_ID = process.env.SHOPIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SHOPIFY_CLIENT_SECRET;
const PORT = process.env.PORT || 3000;

// Helper function to get Shopify Access Token
async function getAccessToken() {
  const res = await fetch(`https://${SHOP}/admin/oauth/access_token`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      grant_type: "client_credentials"
    })
  });

  const text = await res.text();
  let data = {};

  try {
    data = JSON.parse(text);
  } catch {
    throw new Error(`Token response was not JSON: ${text}`);
  }

  if (!res.ok || !data.access_token) {
    throw new Error(data.error_description || data.error || text || "Failed to get access token");
  }

  return data.access_token;
}

// Health check endpoint (Updated version name to verify deployment!)
app.get("/health", (_req, res) => {
  res.json({ ok: true, version: "draft-order-checkout-v2" });
});

// The new Draft Order checkout route
app.post("/create-checkout", async (req, res) => {
  try {
    const body = req.body || {};
    const total = Number(body.total || 0);

    if (!Number.isFinite(total) || total <= 0) {
      return res.status(400).json({ error: "Invalid total." });
    }

    const accessToken = await getAccessToken();

    // GraphQL mutation to create a Draft Order instead of updating a variant
    const graphqlQuery = {
      query: `
        mutation draftOrderCreate($input: DraftOrderInput!) {
          draftOrderCreate(input: $input) {
            draftOrder {
              invoiceUrl
            }
            userErrors {
              message
            }
          }
        }
      `,
      variables: {
        input: {
          lineItems: [
            {
              title: "Transportation Service",
              originalUnitPrice: total.toFixed(2),
              quantity: 1,
              requiresShipping: false
            }
          ]
        }
      }
    };

    // Make the API call to Shopify
    const response = await fetch(`https://${SHOP}/admin/api/2024-04/graphql.json`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Access-Token": accessToken
      },
      body: JSON.stringify(graphqlQuery)
    });

    const data = await response.json();

    const userErrors = data?.data?.draftOrderCreate?.userErrors || [];
    if (data.errors || userErrors.length > 0) {
      console.error("GraphQL Errors:", data.errors || userErrors);
      return res.status(400).json({ error: "Failed to create Draft Order." });
    }

    // Grab the secure invoice link generated by Shopify
    const checkoutUrl = data.data.draftOrderCreate.draftOrder.invoiceUrl;

    console.log(`=== DRAFT ORDER CREATED: $${total.toFixed(2)} ===`);

    // Send the link back to your HTML calculator
    return res.json({
      checkoutUrl,
      total: total.toFixed(2)
    });

  } catch (error) {
    console.error("create-checkout error:", error);
    return res.status(500).json({
      error: error.message || "Server error creating checkout."
    });
  }
});

app.listen(PORT, () => {
  console.log(`DDT backend running on port ${PORT}`);
});
